services:
    primetime.core.block.birthday:
        class: primetime\core\blocks\birthday
        arguments:
            - @cache
            - @dbal.conn
            - @user
        calls:
            - [set_name, [primetime.core.block.birthday]]
        tags:
            - { name: primetime.block }

    primetime.core.blocks.custom:
        class: primetime\core\blocks\custom
        arguments:
            - @cache
            - @dbal.conn
            - @user
            - %tables.primetime.cblocks%
        calls:
            - [set_name, [primetime.core.block.custom]]
        tags:
            - { name: primetime.block }

    primetime.core.block.featured_member:
        class: primetime\core\blocks\featured_member
        arguments:
            - @cache
            - @config
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%
            - %tables.primetime.blocks_config%
        calls:
            - [set_name, [primetime.core.block.featured_member]]
        tags:
            - { name: primetime.block }

    primetime.core.block.forum_poll:
        class: primetime\core\blocks\forum_poll
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @request
            - @user
            - @primetime.core.forum
            - @primetime.core.util
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.core.block.forum_poll]]
        tags:
            - { name: primetime.block }

    primetime.core.block.forum_topics:
        class: primetime\core\blocks\forum_topics
        arguments:
            - @auth
            - @cache
            - @config
            - @user
            - @primetime.core.forum
            - @primetime.core.util
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.core.block.forum_topics]]
        tags:
            - { name: primetime.block }

    primetime.core.block.member_menu:
        class: primetime\core\blocks\member_menu
        arguments:
            - @auth
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.core.block.member_menu]]
        tags:
            - { name: primetime.block }

    primetime.core.block.login:
        class: primetime\core\blocks\login
        arguments:
            - @user
            - %core.root_path%
            - .%core.php_ext%
        calls:
            - [set_name, [primetime.core.block.login]]
        tags:
            - { name: primetime.block }

    primetime.core.block.members:
        class: primetime\core\blocks\members
        arguments:
            - @user
            - @primetime.core.members
        calls:
            - [set_name, [primetime.core.block.members]]
        tags:
            - { name: primetime.block }

    primetime.core.block.menu:
        class: primetime\core\blocks\menu
        arguments:
            - @cache
            - @config
            - @dbal.conn
            - @user
            - @primetime.core.menu.display
            - %tables.primetime.menu%
        calls:
            - [set_name, [primetime.core.block.menu]]
        tags:
            - { name: primetime.block }

    primetime.core.block.mybookmarks:
        class: primetime\core\blocks\mybookmarks
        arguments:
            - @user
            - @primetime.core.forum
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.core.block.mybookmarks]]
        tags:
            - { name: primetime.block }

    primetime.core.blocks.stats:
        class: primetime\core\blocks\stats
        arguments:
            - @config
            - @user
        calls:
            - [set_name, [primetime.core.block.stats]]
        tags:
            - { name: primetime.block }

    primetime.core.block.whats_new:
        class: primetime\core\blocks\whats_new
        arguments:
            - @user
            - @primetime.core.forum
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.core.block.whats_new]]
        tags:
            - { name: primetime.block }

    primetime.core.blocks.whois:
        class: primetime\core\blocks\whois
        arguments:
            - @auth
            - @config
            - @template_context
            - @user
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.core.block.whois]]
        tags:
            - { name: primetime.block }

    primetime.core.blocks.wordgraph:
        class: primetime\core\blocks\wordgraph
        arguments:
            - @auth
            - @content.visibility
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.core.block.wordgraph]]
        tags:
            - { name: primetime.block }