services:
    primetime.primetime.block.birthday:
        class: primetime\primetime\blocks\birthday
        arguments:
            - @cache
            - @dbal.conn
            - @user
        calls:
            - [set_name, [primetime.primetime.block.birthday]]
        tags:
            - { name: primetime.block }

    primetime.primetime.block.featured_member:
        class: primetime\primetime\blocks\featured_member
        arguments:
            - @cache
            - @config
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%
            - %tables.primetime.blocks_config%
        calls:
            - [set_name, [primetime.primetime.block.featured_member]]
        tags:
            - { name: primetime.block }

    primetime.primetime.block.forum_poll:
        class: primetime\primetime\blocks\forum_poll
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @request
            - @user
            - @primetime.primetime.forum
            - @primetime.primetime
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.primetime.block.forum_poll]]
        tags:
            - { name: primetime.block }

    primetime.primetime.block.forum_topics:
        class: primetime\primetime\blocks\forum_topics
        arguments:
            - @auth
            - @cache
            - @config
            - @user
            - @primetime.primetime.forum
            - @primetime.primetime
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.primetime.block.forum_topics]]
        tags:
            - { name: primetime.block }

    primetime.primetime.blocks.html:
        class: primetime\primetime\blocks\html
        arguments:
            - @user
        calls:
            - [set_name, [primetime.primetime.block.html]]
        tags:
            - { name: primetime.block }

    primetime.primetime.block.member_menu:
        class: primetime\primetime\blocks\member_menu
        arguments:
            - @auth
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.primetime.block.member_menu]]
        tags:
            - { name: primetime.block }

    primetime.primetime.block.login:
        class: primetime\primetime\blocks\login
        arguments:
            - @user
            - %core.root_path%
            - .%core.php_ext%
        calls:
            - [set_name, [primetime.primetime.block.login]]
        tags:
            - { name: primetime.block }

    primetime.primetime.block.members:
        class: primetime\primetime\blocks\members
        arguments:
            - @user
            - @primetime.primetime.members
        calls:
            - [set_name, [primetime.primetime.block.members]]
        tags:
            - { name: primetime.block }

    primetime.primetime.block.menu:
        class: primetime\primetime\blocks\menu
        arguments:
            - @cache
            - @config
            - @dbal.conn
            - @user
            - @primetime.primetime.menu.display
            - %tables.primetime.menu%
        calls:
            - [set_name, [primetime.primetime.block.menu]]
        tags:
            - { name: primetime.block }

    primetime.primetime.block.mybookmarks:
        class: primetime\primetime\blocks\mybookmarks
        arguments:
            - @user
            - @primetime.primetime.forum
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.primetime.block.mybookmarks]]
        tags:
            - { name: primetime.block }

    primetime.primetime.blocks.stats:
        class: primetime\primetime\blocks\stats
        arguments:
            - @config
            - @user
        calls:
            - [set_name, [primetime.primetime.block.stats]]
        tags:
            - { name: primetime.block }

    primetime.primetime.block.whats_new:
        class: primetime\primetime\blocks\whats_new
        arguments:
            - @user
            - @primetime.primetime.forum
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.primetime.block.whats_new]]
        tags:
            - { name: primetime.block }

    primetime.primetime.blocks.whois:
        class: primetime\primetime\blocks\whois
        arguments:
            - @auth
            - @config
            - @template_context
            - @user
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.primetime.block.whois]]
        tags:
            - { name: primetime.block }

    primetime.primetime.blocks.wordgraph:
        class: primetime\primetime\blocks\wordgraph
        arguments:
            - @auth
            - @content.visibility
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.primetime.block.wordgraph]]
        tags:
            - { name: primetime.block }