services:
    primetime.block.login:
        class: primetime\primetime\blocks\login
        arguments:
            - @user
            - %core.root_path%
            - .%core.php_ext%
        calls:
            - [set_name, [primetime.block.login]]
        tags:
            - { name: primetime.block }

    primetime.block.menu:
        class: primetime\primetime\blocks\menu
        arguments:
            - @dbal.conn
            - @user
            - @primetime.menu.display
            - %tables.primetime.menu%
        calls:
            - [set_name, [primetime.block.menu]]
        tags:
            - { name: primetime.block }

    primetime.blocks.myblock:
        class: primetime\primetime\blocks\myblock
        arguments:
            - @user
        calls:
            - [set_name, [primetime.block.myblock]]
        tags:
            - { name: primetime.block }

    primetime.blocks.stats:
        class: primetime\primetime\blocks\stats
        arguments:
            - @config
            - @user
        calls:
            - [set_name, [primetime.block.stats]]
        tags:
            - { name: primetime.block }

    primetime.blocks.whois:
        class: primetime\primetime\blocks\whois
        arguments:
            - @config
            - @template_context
        calls:
            - [set_name, [primetime.block.whois]]
        tags:
            - { name: primetime.block }