services:
    primetime.block.birthday:
        class: primetime\primetime\blocks\birthday
        arguments:
            - @cache.driver
            - @dbal.conn
            - @user
        calls:
            - [set_name, [primetime.block.birthday]]
        tags:
            - { name: primetime.block }

    primetime.blocks.custom:
        class: primetime\primetime\blocks\custom
        arguments:
            - @user
        calls:
            - [set_name, [primetime.block.custom]]
        tags:
            - { name: primetime.block }

    primetime.block.featured_member:
        class: primetime\primetime\blocks\featured_member
        arguments:
            - @cache.driver
            - @config
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%
            - %tables.primetime.blocks_config%
        calls:
            - [set_name, [primetime.block.featured_member]]
        tags:
            - { name: primetime.block }

    primetime.block.forum_topics:
        class: primetime\primetime\blocks\forum_topics
        arguments:
            - @auth
            - @cache.driver
            - @config
            - @user
            - @primetime.forum
            - @primetime
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.block.forum_topics]]
        tags:
            - { name: primetime.block }

    primetime.block.member_menu:
        class: primetime\primetime\blocks\member_menu
        arguments:
            - @auth
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%
        calls:
            - [set_name, [primetime.block.member_menu]]
        tags:
            - { name: primetime.block }

    primetime.block.login:
        class: primetime\primetime\blocks\login
        arguments:
            - @user
            - %core.root_path%
            - .%core.php_ext%
        calls:
            - [set_name, [primetime.block.login]]
        tags:
            - { name: primetime.block }

    primetime.block.members:
        class: primetime\primetime\blocks\members
        arguments:
            - @user
            - @primetime.members
        calls:
            - [set_name, [primetime.block.members]]
        tags:
            - { name: primetime.block }

    primetime.block.menu:
        class: primetime\primetime\blocks\menu
        arguments:
            - @cache.driver
            - @dbal.conn
            - @user
            - @primetime.menu.display
            - %tables.primetime.menu%
        calls:
            - [set_name, [primetime.block.menu]]
        tags:
            - { name: primetime.block }

    primetime.blocks.stats:
        class: primetime\primetime\blocks\stats
        arguments:
            - @config
            - @user
        calls:
            - [set_name, [primetime.block.stats]]
        tags:
            - { name: primetime.block }

    primetime.blocks.whois:
        class: primetime\primetime\blocks\whois
        arguments:
            - @config
            - @template_context
        calls:
            - [set_name, [primetime.block.whois]]
        tags:
            - { name: primetime.block }