services:

    primetime.primetime.blocks.admin.controller:
        class: primetime\primetime\controller\blocks_admin
        arguments:
            - @auth
            - @config
            - @request
            - @user
            - @primetime.primetime.blocks.manager

    primetime.primetime.forum.controller:
        class: primetime\primetime\controller\forum
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%

    primetime.primetime.menu.admin.controller:
        class: primetime\primetime\controller\menu_admin
        arguments:
            - @request
            - @user
            - @template
            - @primetime.primetime.menu.builder
            - %tables.primetime.menu%