services:

    primetime.base.blocks.admin.controller:
        class: primetime\base\controller\blocks_admin
        arguments:
            - @auth
            - @config
            - @request
            - @user
            - @primetime.base.blocks.manager

    primetime.base.forum.controller:
        class: primetime\base\controller\forum
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%

    primetime.base.menu.admin.controller:
        class: primetime\base\controller\menu_admin
        arguments:
            - @request
            - @user
            - @template
            - @primetime.base.menu.builder
            - %tables.primetime.menu%