services:

    primetime.core.blocks.admin.controller:
        class: primetime\core\controller\blocks_admin
        arguments:
            - @auth
            - @config
            - @request
            - @user
            - @primetime.core.blocks.manager

    primetime.core.forum.controller:
        class: primetime\core\controller\forum
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%

    primetime.core.menu.admin.controller:
        class: primetime\core\controller\menu_admin
        arguments:
            - @request
            - @user
            - @template
            - @primetime.core.menu.builder
            - %tables.primetime.menu%