services:

    blitze.sitemaker.blocks.admin.controller:
        class: blitze\sitemaker\controller\blocks_admin
        arguments:
            - @auth
            - @config
            - @request
            - @user
            - @blitze.sitemaker.blocks.manager

    blitze.sitemaker.forum.controller:
        class: blitze\sitemaker\controller\forum
        arguments:
            - @config
            - @controller.helper
            - @template
            - @user
            - %core.root_path%
            - %core.php_ext%

    blitze.sitemaker.menu.admin.controller:
        class: blitze\sitemaker\controller\menu_admin
        arguments:
            - @request
            - @user
            - @template
            - @blitze.sitemaker.menu.builder
