services:
    primetime.form.builder:
        class: primetime\primetime\core\form\builder
        arguments:
            - @request
            - @primetime.form.fields_collection
            - @user
            - @primetime
            - @primetime.template

    primetime.form.fields_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: form.field }

    form.field.checkbox:
        class: primetime\primetime\core\form\field\checkbox
        arguments:
            - @request
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.color:
        class: primetime\primetime\core\form\field\color
        arguments:
            - @request
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.date:
        class: primetime\primetime\core\form\field\date
        arguments:
            - @request
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.datetime:
        class: primetime\primetime\core\form\field\datetime
        arguments:
            - @request
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.editor:
        class: primetime\primetime\core\form\field\editor
        arguments:
            - @request
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.email:
        class: primetime\primetime\core\form\field\email
        arguments:
            - @request
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.hidden:
        class: primetime\primetime\core\form\field\hidden
        arguments:
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.multiple:
        class: primetime\primetime\core\form\field\multiple
        arguments:
            - @request
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.number:
        class: primetime\primetime\core\form\field\number
        arguments:
            - @request
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.password:
        class: primetime\primetime\core\form\field\password
        arguments:
            - @request
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.radio:
        class: primetime\primetime\core\form\field\radio
        arguments:
            - @request
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.range:
        class: primetime\primetime\core\form\field\range
        arguments:
            - @request
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.reset:
        class: primetime\primetime\core\form\field\reset
        arguments:
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.select:
        class: primetime\primetime\core\form\field\select
        arguments:
            - @request
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.submit:
        class: primetime\primetime\core\form\field\submit
        arguments:
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.telephone:
        class: primetime\primetime\core\form\field\telephone
        arguments:
            - @request
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.text:
        class: primetime\primetime\core\form\field\text
        arguments:
            - @request
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.textarea:
        class: primetime\primetime\core\form\field\textarea
        arguments:
            - @request
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.time:
        class: primetime\primetime\core\form\field\time
        arguments:
            - @request
            - @primetime.template
        tags:
            - { name: form.field }

    form.field.url:
        class: primetime\primetime\core\form\field\url
        arguments:
            - @request
            - @primetime.template
        tags:
            - { name: form.field }