parameters:
    tables.primetime.blocks: %core.table_prefix%blocks
    tables.primetime.blocks_config: %core.table_prefix%blocks_config
    tables.primetime.block_positions: %core.table_prefix%block_positions