parameters:
    tables.sitemaker.blocks: %core.table_prefix%pt_blocks
    tables.sitemaker.blocks_config: %core.table_prefix%pt_blocks_config
    tables.sitemaker.block_routes: %core.table_prefix%pt_block_routes
    tables.sitemaker.cblocks: %core.table_prefix%pt_cblocks
    tables.sitemaker.menu: %core.table_prefix%pt_menus
    tables.sitemaker.menu_items: %core.table_prefix%pt_menu_items