primetime_core_blocks_admin:
    path: /blocks/{action}/{id}/{block}
    defaults: { _controller: primetime.core.blocks.admin.controller:handle, id: 0, block: '', _format: json }
    requirements:
        id: \d+
        _format: json

primetime_core_menu_admin:
    path: /menu/admin/{action}/{item_id}
    defaults: { _controller: primetime.core.menu.admin.controller:handle, item_id: 0 }
    requirements:
        item_id: \d+
        _format: json

primetime_core_forum:
    path: /forum
    defaults: { _controller: primetime.core.forum.controller:handle }