primetime_base_blocks_admin:
    path: /blocks/{action}/{id}/{block}
    defaults: { _controller: primetime.base.blocks.admin.controller:handle, id: 0, block: '', _format: json }
    requirements:
        id: \d+
        _format: json

primetime_base_menu_admin:
    path: /menu/admin/{action}/{item_id}
    defaults: { _controller: primetime.base.menu.admin.controller:handle, item_id: 0 }
    requirements:
        item_id: \d+
        _format: json

primetime_base_forum:
    path: /forum
    defaults: { _controller: primetime.base.forum.controller:handle }