primetime.blocks.admin:
    pattern: /blocks/{action}/{id}/{block}
    defaults: { _controller: primetime.blocks.admin:handle, id: 0, block: '', _format: json }
    requirements:
        id: \d+
        _format: json

primetime.menu.admin:
    pattern: menu/admin/{action}/{item_id}
    defaults: { _controller: primetime.menu.admin:handle, item_id: 0 }
    requirements:
        item_id: \d+
