blitze_sitemaker_blocks_admin:
    path: /blocks/{action}
    defaults: { _controller: blitze.sitemaker.blocks.admin.controller:handle, _format: json }
    requirements:
        _format: json

blitze_sitemaker_menu_admin:
    path: /menu/admin/{action}/{item_id}
    defaults: { _controller: blitze.sitemaker.menu.admin.controller:handle, item_id: 0 }
    requirements:
        item_id: \d+
        _format: json

blitze_sitemaker_forum:
    path: /forum
    defaults: { _controller: blitze.sitemaker.forum.controller:handle }
