imports:
    - { resource: parameters.yml }
    - { resource: blocks.yml }
    - { resource: controllers.yml }

services:

    blitze.sitemaker.blocks.builder:
        class: blitze\sitemaker\services\blocks\builder
        arguments:
            - @cache
            - @config
            - @dbal.conn
            - @service_container
            - @template
            - @user
            - @blitze.sitemaker.icon_picker
            - @blitze.sitemaker.util
            - %core.php_ext%
            - %tables.sitemaker.blocks%
            - %tables.sitemaker.block_routes%

    blitze.sitemaker.blocks.cfg_fields:
        class: blitze\sitemaker\services\blocks\cfg_fields
        arguments:
            - @user

    blitze.sitemaker.blocks.display:
        class: blitze\sitemaker\services\blocks\display
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @service_container
            - @request
            - @template
            - @user
            - @blitze.sitemaker.util
            - @blitze.sitemaker.template
            - %tables.sitemaker.blocks%
            - %tables.sitemaker.blocks_config%
            - %tables.sitemaker.block_routes%

    blitze.sitemaker.block_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: sitemaker.block }

    blitze.sitemaker.blocks.factory:
        class: blitze\sitemaker\services\blocks\factory
        arguments:
            - @blitze.sitemaker.block_collection

    blitze.sitemaker.blocks.manager:
        class: blitze\sitemaker\services\blocks\manager
        arguments:
            - @cache
            - @config
            - @dbal.conn
            - @service_container
            - @request
            - @template
            - @user
            - @blitze.sitemaker.template
            - %core.root_path%
            - %core.php_ext%
            - %tables.sitemaker.blocks%
            - %tables.sitemaker.blocks_config%
            - %tables.sitemaker.block_routes%

    blitze.sitemaker.cron.blocks_cleanup:
        class: blitze\sitemaker\cron\blocks_cleanup
        arguments:
            - @config
            - @dbal.conn
            - @blitze.sitemaker.blocks.manager
            - @blitze.sitemaker.url_checker
            - %tables.sitemaker.blocks%
            - %tables.sitemaker.cblocks%
        calls:
            - [set_name, [blitze.sitemaker.cron.blocks_cleanup]]
        tags:
            - { name: cron.task }

    blitze.sitemaker.forum.data:
        class: blitze\sitemaker\services\forum\data
        arguments:
            - @auth
            - @config
            - @content.visibility
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%

    blitze.sitemaker.forum.manager:
        class: blitze\sitemaker\services\forum\manager
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%

    blitze.sitemaker.icon_picker:
        class: blitze\sitemaker\services\icon_picker
        arguments:
            - @user
            - @blitze.sitemaker.util
            - @blitze.sitemaker.template

    blitze.sitemaker.listener:
        class: blitze\sitemaker\event\listener
        arguments:
            - @cache
            - @config
            - @request
            - @service_container
            - @template
            - @user
            - @blitze.sitemaker.util
            - @blitze.sitemaker.blocks.display
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }

    blitze.sitemaker.members:
        class: blitze\sitemaker\services\members
        arguments:
            - @dbal.conn
            - @user
            - @blitze.sitemaker.util
            - @blitze.sitemaker.template
            - %core.root_path%
            - %core.php_ext%

    blitze.sitemaker.menu.builder:
        class: blitze\sitemaker\services\menu\builder
        arguments:
            - @cache
            - @dbal.conn
            - @blitze.sitemaker.util
            - %tables.sitemaker.menu%
            - %tables.sitemaker.menu_items%
            - 'item_id'

    blitze.sitemaker.menu.display:
        class: blitze\sitemaker\services\menu\display
        arguments:
            - @dbal.conn
            - @user
            - %tables.sitemaker.menu_items%
            - 'item_id'

    blitze.sitemaker.template:
        class: blitze\sitemaker\services\template
        arguments:
            - @path_helper
            - @config
            - @user
            - @blitze.sitemaker.template_context
            - @ext.manager

    blitze.sitemaker.template_context:
        class: phpbb\template\context

    blitze.sitemaker.url_checker:
        class: blitze\sitemaker\services\url_checker

    blitze.sitemaker.util:
        class: blitze\sitemaker\services\util
        arguments:
            - @path_helper
            - @template
            - @template_context
            - @user
