imports:
    - { resource: parameters.yml }
    - { resource: blocks.yml }
    - { resource: controllers.yml }

services:

    primetime.primetime:
        class: primetime\primetime\core\primetime
        arguments:
            - @path_helper
            - @template

    primetime.primetime.blocks.display:
        class: primetime\primetime\core\blocks\display
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @service_container
            - @request
            - @template
            - @user
            - @primetime.primetime
            - @primetime.primetime.template
            - %tables.primetime.blocks%
            - %tables.primetime.blocks_config%
            - %tables.primetime.block_routes%

    primetime.primetime.blocks.manager:
        class: primetime\primetime\core\blocks\manager
        arguments:
            - @cache
            - @config
            - @dbal.conn
            - @service_container
            - @request
            - @template
            - @user
            - @primetime.primetime.icon_picker
            - @primetime.primetime
            - @primetime.primetime.template
            - %tables.primetime.blocks%
            - %tables.primetime.blocks_config%
            - %tables.primetime.block_routes%
            - %core.root_path%
            - %core.php_ext%

    primetime.primetime.block_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: primetime.block }

    primetime.primetime.blocks.factory:
        class: primetime\primetime\core\blocks\factory
        arguments:
            - @primetime.primetime.block_collection

    primetime.primetime.cron.blocks_cleanup:
        class: primetime\primetime\cron\blocks_cleanup
        arguments:
            - @config
            - @dbal.conn
            - @primetime.primetime.blocks.manager
        calls:
            - [set_name, [primetime.primetime.cron.blocks_cleanup]]
        tags:
            - { name: cron.task }

    primetime.primetime.forum:
        class: primetime\primetime\core\forum\query
        arguments:
            - @auth
            - @config
            - @content.visibility
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%
            - @primetime.primetime

    primetime.primetime.forum.manager:
        class: primetime\primetime\core\forum\manager
        arguments:
            - @auth
            - @cache
            - @config
            - @user
            - %core.root_path%
            - %core.php_ext%

    primetime.primetime.icon_picker:
        class: primetime\primetime\core\icon_picker
        arguments:
            - @user
            - @primetime.primetime
            - @primetime.primetime.template

    primetime.primetime.listener:
        class: primetime\primetime\event\listener
        arguments:
            - @cache
            - @config
            - @request
            - @service_container
            - @template
            - @user
            - @primetime.primetime
            - @primetime.primetime.blocks.display
            - %core.root_path%
        tags:
            - { name: event.listener }

    primetime.primetime.members:
        class: primetime\primetime\core\members
        arguments:
            - @dbal.conn
            - @user
            - @primetime.primetime.template
            - %core.root_path%
            - %core.php_ext%

    primetime.primetime.menu.builder:
        class: primetime\primetime\core\menu\builder
        arguments:
            - @cache
            - @dbal.conn
            - @primetime.primetime
            - %tables.primetime.menu%
            - %tables.primetime.menu_items%
            - 'item_id'

    primetime.primetime.menu.display:
        class: primetime\primetime\core\menu\display
        arguments:
            - @dbal.conn
            - @primetime.primetime
            - %tables.primetime.menu_items%
            - 'item_id'

    primetime.primetime.template_context:
        class: phpbb\template\context

    primetime.primetime.template:
        class: primetime\primetime\core\template
        arguments:
            - @path_helper
            - @config
            - @user
            - @primetime.primetime.template_context
            - @ext.manager
