imports:
    - { resource: parameters.yml }
    - { resource: blocks.yml }
    - { resource: controllers.yml }

services:

    primetime.core.util:
        class: primetime\core\services\util
        arguments:
            - @path_helper
            - @template

    primetime.core.blocks.builder:
        class: primetime\core\services\blocks\builder
        arguments:
            - @cache
            - @config
            - @dbal.conn
            - @service_container
            - @template
            - @user
            - @primetime.core.icon_picker
            - @primetime.core.util
            - %core.php_ext%

    primetime.core.blocks.display:
        class: primetime\core\services\blocks\display
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @service_container
            - @request
            - @template
            - @user
            - @primetime.core.util
            - @primetime.core.template

    primetime.core.blocks.manager:
        class: primetime\core\services\blocks\manager
        arguments:
            - @cache
            - @config
            - @dbal.conn
            - @service_container
            - @request
            - @template
            - @user
            - @primetime.core.template
            - %core.root_path%
            - %core.php_ext%

    primetime.core.block_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: primetime.block }

    primetime.core.blocks.factory:
        class: primetime\core\services\blocks\factory
        arguments:
            - @primetime.core.block_collection

    primetime.core.cron.blocks_cleanup:
        class: primetime\core\cron\blocks_cleanup
        arguments:
            - @config
            - @dbal.conn
            - @primetime.core.blocks.manager
            - %tables.primetime.blocks%
            - %tables.primetime.cblocks%
        calls:
            - [set_name, [primetime.core.cron.blocks_cleanup]]
        tags:
            - { name: cron.task }

    primetime.core.forum:
        class: primetime\core\services\forum\query
        arguments:
            - @auth
            - @config
            - @content.visibility
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%
            - @primetime.core.util

    primetime.core.forum.manager:
        class: primetime\core\services\forum\manager
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%

    primetime.core.icon_picker:
        class: primetime\core\services\icon_picker
        arguments:
            - @user
            - @primetime.core.util
            - @primetime.core.template

    primetime.core.listener:
        class: primetime\core\event\listener
        arguments:
            - @cache
            - @config
            - @request
            - @service_container
            - @template
            - @user
            - @primetime.core.util
            - @primetime.core.blocks.display
            - %tables.primetime.blocks%
            - %tables.primetime.blocks_config%
            - %tables.primetime.block_routes%
            - %core.root_path%
        tags:
            - { name: event.listener }

    primetime.core.members:
        class: primetime\core\services\members
        arguments:
            - @dbal.conn
            - @user
            - @primetime.core.template
            - %core.root_path%
            - %core.php_ext%

    primetime.core.menu.builder:
        class: primetime\core\services\menu\builder
        arguments:
            - @cache
            - @dbal.conn
            - @primetime.core.util
            - %tables.primetime.menu%
            - %tables.primetime.menu_items%
            - 'item_id'

    primetime.core.menu.display:
        class: primetime\core\services\menu\display
        arguments:
            - @dbal.conn
            - @primetime.core.util
            - %tables.primetime.menu_items%
            - 'item_id'

    primetime.core.template_context:
        class: phpbb\template\context

    primetime.core.template:
        class: primetime\core\services\template
        arguments:
            - @path_helper
            - @config
            - @user
            - @primetime.core.template_context
            - @ext.manager
