imports:
    - { resource: parameters.yml }
    - { resource: blocks.yml }
    - { resource: controllers.yml }

services:

    primetime.base.util:
        class: primetime\base\services\util
        arguments:
            - @path_helper
            - @template

    primetime.base.blocks.display:
        class: primetime\base\services\blocks\display
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @service_container
            - @request
            - @template
            - @user
            - @primetime.base.util
            - @primetime.base.template
            - %tables.primetime.blocks%
            - %tables.primetime.blocks_config%
            - %tables.primetime.block_routes%

    primetime.base.blocks.manager:
        class: primetime\base\services\blocks\manager
        arguments:
            - @cache
            - @config
            - @dbal.conn
            - @service_container
            - @request
            - @template
            - @user
            - @primetime.base.icon_picker
            - @primetime.base.util
            - @primetime.base.template
            - %tables.primetime.blocks%
            - %tables.primetime.blocks_config%
            - %tables.primetime.block_routes%
            - %core.root_path%
            - %core.php_ext%

    primetime.base.block_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: primetime.block }

    primetime.base.blocks.factory:
        class: primetime\base\services\blocks\factory
        arguments:
            - @primetime.base.block_collection

    primetime.base.cron.blocks_cleanup:
        class: primetime\base\cron\blocks_cleanup
        arguments:
            - @config
            - @dbal.conn
            - @primetime.base.blocks.manager
        calls:
            - [set_name, [primetime.base.cron.blocks_cleanup]]
        tags:
            - { name: cron.task }

    primetime.base.forum:
        class: primetime\base\services\forum\query
        arguments:
            - @auth
            - @config
            - @content.visibility
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%
            - @primetime.base.util

    primetime.base.forum.manager:
        class: primetime\base\services\forum\manager
        arguments:
            - @auth
            - @cache
            - @config
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%

    primetime.base.icon_picker:
        class: primetime\base\services\icon_picker
        arguments:
            - @user
            - @primetime.base.util
            - @primetime.base.template

    primetime.base.listener:
        class: primetime\base\event\listener
        arguments:
            - @cache
            - @config
            - @request
            - @service_container
            - @template
            - @user
            - @primetime.base.util
            - @primetime.base.blocks.display
            - %core.root_path%
        tags:
            - { name: event.listener }

    primetime.base.members:
        class: primetime\base\services\members
        arguments:
            - @dbal.conn
            - @user
            - @primetime.base.template
            - %core.root_path%
            - %core.php_ext%

    primetime.base.menu.builder:
        class: primetime\base\services\menu\builder
        arguments:
            - @cache
            - @dbal.conn
            - @primetime.base.util
            - %tables.primetime.menu%
            - %tables.primetime.menu_items%
            - 'item_id'

    primetime.base.menu.display:
        class: primetime\base\services\menu\display
        arguments:
            - @dbal.conn
            - @primetime.base.util
            - %tables.primetime.menu_items%
            - 'item_id'

    primetime.base.template_context:
        class: phpbb\template\context

    primetime.base.template:
        class: primetime\base\services\template
        arguments:
            - @path_helper
            - @config
            - @user
            - @primetime.base.template_context
            - @ext.manager
