imports:
    - { resource: parameters.yml }
    - { resource: blocks.yml }

services:

    primetime:
        class: primetime\primetime\core\primetime
        arguments:
            - @user
            - @template
            - @primetime.template
            - @path_helper

    primetime.icon_picker:
        class: primetime\primetime\core\icon_picker
        arguments:
            - @primetime.template
            - @user
            - @primetime

    primetime.blocks.admin:
        class: primetime\primetime\controller\blocks_admin
        arguments:
            - @auth
            - @request
            - @user
            - @primetime.blocks.manager

    primetime.blocks.display:
        class: primetime\primetime\core\blocks\display
        arguments:
            - @auth
            - @cache.driver
            - @dbal.conn
            - @request
            - @template
            - @user
            - @primetime.template
            - @primetime
            - %tables.primetime.blocks%
            - %tables.primetime.blocks_config%
            - %tables.primetime.block_routes%

    primetime.blocks.manager:
        class: primetime\primetime\core\blocks\manager
        arguments:
            - @cache.driver
            - @dbal.conn
            - @request
            - @template
            - @user
            - @primetime.template
            - @primetime.icon_picker
            - @primetime
            - %tables.primetime.blocks%
            - %tables.primetime.blocks_config%
            - %tables.primetime.block_routes%

    primetime.block_collection:
        class: phpbb\di\service_collection
        arguments:
            - @service_container
        tags:
            - { name: service_collection, tag: primetime.block }

    primetime.blocks.factory:
        class: primetime\primetime\core\blocks\factory
        arguments:
            - @primetime.block_collection

    primetime.listener:
        class: primetime\primetime\event\listener
        arguments:
            - @request
            - @primetime
            - @primetime.blocks.display
        tags:
            - { name: event.listener }

    primetime.template_context:
        class: phpbb\template\context

    primetime.template:
        class: \primetime\primetime\core\blocks\template
        arguments:
            - @path_helper
            - @config
            - @user
            - @primetime.template_context
            - @ext.manager

